const dbConfig = require("../db.config.js");
const mongoose = require("mongoose");
mongoose.Promise = global.Promise;
const db = {};
db.mongoose = mongoose;
db.url = dbConfig.url;
db.articles = require("./article.model.js")(mongoose);
db.users = require("./user.model.js")(mongoose);
module.exports = db;